FROM node:16-alpine
ARG _CONTENTFUL_SPACE_ID
ARG _CONTENTFUL_ACCESS_TOKEN
ENV NEXT_PUBLIC_CONTENTFUL_SPACE_ID {${_CONTENTFUL_SPACE_ID}}
ENV NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN {${_CONTENTFUL_ACCESS_TOKEN}}

WORKDIR /usr/app

COPY . .

RUN npm ci

RUN npm run build

CMD [ "npm", "start" ]